services:
  backend:
    container_name: backend
    restart: unless-stopped
    env_file: .env
    build:
      context: ./backend
      dockerfile: Dockerfile
    depends_on:
      - postgres
    volumes:
      - ./logs:/app/logs
    expose:
      - 8000

  postgres:
    container_name: postgres
    restart: unless-stopped
    image: postgres:latest
    env_file: .env
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    ports:
      - 5432:5432

  mongo:
    image: mongo
    restart: unless-stopped
    env_file: .env
    ports:
      - 27017:27017
    volumes:
      - mongo-data:/data/db
      - ./create_local_user.js:/docker-entrypoint-initdb.d/create_local_user.js
